"""
Mapping of country names to their ISO 3166-1 alpha-2 country codes.
Used for scraping from specific geographic locations.
"""

COUNTRY_CODES = {
    # North America
    "us": "us",
    "usa": "us",
    "united states": "us",
    "united states of america": "us",
    "ca": "ca",
    "canada": "ca",
    "mx": "mx",
    "mexico": "mx",
    "cu": "cu",
    "cuba": "cu",
    "do": "do",
    "dominican republic": "do",
    "ht": "ht",
    "haiti": "ht",
    "jm": "jm",
    "jamaica": "jm",
    "pr": "pr",
    "puerto rico": "pr",
    # Central America
    "bz": "bz",
    "belize": "bz",
    "cr": "cr",
    "costa rica": "cr",
    "sv": "sv",
    "el salvador": "sv",
    "gt": "gt",
    "guatemala": "gt",
    "hn": "hn",
    "honduras": "hn",
    "ni": "ni",
    "nicaragua": "ni",
    "pa": "pa",
    "panama": "pa",
    # South America
    "ar": "ar",
    "argentina": "ar",
    "bo": "bo",
    "bolivia": "bo",
    "br": "br",
    "brazil": "br",
    "cl": "cl",
    "chile": "cl",
    "co": "co",
    "colombia": "co",
    "ec": "ec",
    "ecuador": "ec",
    "gy": "gy",
    "guyana": "gy",
    "py": "py",
    "paraguay": "py",
    "pe": "pe",
    "peru": "pe",
    "sr": "sr",
    "suriname": "sr",
    "uy": "uy",
    "uruguay": "uy",
    "ve": "ve",
    "venezuela": "ve",
    # Europe
    "al": "al",
    "albania": "al",
    "ad": "ad",
    "andorra": "ad",
    "at": "at",
    "austria": "at",
    "by": "by",
    "belarus": "by",
    "be": "be",
    "belgium": "be",
    "ba": "ba",
    "bosnia and herzegovina": "ba",
    "bg": "bg",
    "bulgaria": "bg",
    "hr": "hr",
    "croatia": "hr",
    "cz": "cz",
    "czech republic": "cz",
    "dk": "dk",
    "denmark": "dk",
    "ee": "ee",
    "estonia": "ee",
    "fi": "fi",
    "finland": "fi",
    "fr": "fr",
    "france": "fr",
    "de": "de",
    "germany": "de",
    "gr": "gr",
    "greece": "gr",
    "hu": "hu",
    "hungary": "hu",
    "is": "is",
    "iceland": "is",
    "ie": "ie",
    "ireland": "ie",
    "it": "it",
    "italy": "it",
    "lv": "lv",
    "latvia": "lv",
    "li": "li",
    "liechtenstein": "li",
    "lt": "lt",
    "lithuania": "lt",
    "lu": "lu",
    "luxembourg": "lu",
    "mt": "mt",
    "malta": "mt",
    "md": "md",
    "moldova": "md",
    "mc": "mc",
    "monaco": "mc",
    "me": "me",
    "montenegro": "me",
    "nl": "nl",
    "netherlands": "nl",
    "mk": "mk",
    "north macedonia": "mk",
    "no": "no",
    "norway": "no",
    "pl": "pl",
    "poland": "pl",
    "pt": "pt",
    "portugal": "pt",
    "ro": "ro",
    "romania": "ro",
    "ru": "ru",
    "russia": "ru",
    "russian federation": "ru",
    "sm": "sm",
    "san marino": "sm",
    "rs": "rs",
    "serbia": "rs",
    "sk": "sk",
    "slovakia": "sk",
    "si": "si",
    "slovenia": "si",
    "es": "es",
    "spain": "es",
    "se": "se",
    "sweden": "se",
    "ch": "ch",
    "switzerland": "ch",
    "ua": "ua",
    "ukraine": "ua",
    "uk": "gb",
    "united kingdom": "gb",
    "great britain": "gb",
    "gb": "gb",
    "va": "va",
    "vatican city": "va",
    # Asia
    "af": "af",
    "afghanistan": "af",
    "am": "am",
    "armenia": "am",
    "az": "az",
    "azerbaijan": "az",
    "bh": "bh",
    "bahrain": "bh",
    "bd": "bd",
    "bangladesh": "bd",
    "bt": "bt",
    "bhutan": "bt",
    "bn": "bn",
    "brunei": "bn",
    "kh": "kh",
    "cambodia": "kh",
    "cn": "cn",
    "china": "cn",
    "peoples republic of china": "cn",
    "cy": "cy",
    "cyprus": "cy",
    "ge": "ge",
    "georgia": "ge",
    "in": "in",
    "india": "in",
    "id": "id",
    "indonesia": "id",
    "ir": "ir",
    "iran": "ir",
    "iq": "iq",
    "iraq": "iq",
    "il": "il",
    "israel": "il",
    "jp": "jp",
    "japan": "jp",
    "jo": "jo",
    "jordan": "jo",
    "kz": "kz",
    "kazakhstan": "kz",
    "kw": "kw",
    "kuwait": "kw",
    "kg": "kg",
    "kyrgyzstan": "kg",
    "la": "la",
    "laos": "la",
    "lb": "lb",
    "lebanon": "lb",
    "my": "my",
    "malaysia": "my",
    "mv": "mv",
    "maldives": "mv",
    "mn": "mn",
    "mongolia": "mn",
    "mm": "mm",
    "myanmar": "mm",
    "burma": "mm",
    "np": "np",
    "nepal": "np",
    "kp": "kp",
    "north korea": "kp",
    "dprk": "kp",
    "om": "om",
    "oman": "om",
    "pk": "pk",
    "pakistan": "pk",
    "ph": "ph",
    "philippines": "ph",
    "qa": "qa",
    "qatar": "qa",
    "sa": "sa",
    "saudi arabia": "sa",
    "sg": "sg",
    "singapore": "sg",
    "kr": "kr",
    "south korea": "kr",
    "korea": "kr",
    "lk": "lk",
    "sri lanka": "lk",
    "sy": "sy",
    "syria": "sy",
    "tw": "tw",
    "taiwan": "tw",
    "tj": "tj",
    "tajikistan": "tj",
    "th": "th",
    "thailand": "th",
    "tr": "tr",
    "turkey": "tr",
    "tm": "tm",
    "turkmenistan": "tm",
    "ae": "ae",
    "uae": "ae",
    "united arab emirates": "ae",
    "uz": "uz",
    "uzbekistan": "uz",
    "vn": "vn",
    "vietnam": "vn",
    "ye": "ye",
    "yemen": "ye",
    # Africa
    "dz": "dz",
    "algeria": "dz",
    "ao": "ao",
    "angola": "ao",
    "bj": "bj",
    "benin": "bj",
    "bw": "bw",
    "botswana": "bw",
    "bf": "bf",
    "burkina faso": "bf",
    "bi": "bi",
    "burundi": "bi",
    "cm": "cm",
    "cameroon": "cm",
    "cv": "cv",
    "cape verde": "cv",
    "cf": "cf",
    "central african republic": "cf",
    "td": "td",
    "chad": "td",
    "km": "km",
    "comoros": "km",
    "cg": "cg",
    "congo": "cg",
    "cd": "cd",
    "drc": "cd",
    "democratic republic of the congo": "cd",
    "ci": "ci",
    "cote divoire": "ci",
    "ivory coast": "ci",
    "dj": "dj",
    "djibouti": "dj",
    "eg": "eg",
    "egypt": "eg",
    "gq": "gq",
    "equatorial guinea": "gq",
    "er": "er",
    "eritrea": "er",
    "et": "et",
    "ethiopia": "et",
    "ga": "ga",
    "gabon": "ga",
    "gm": "gm",
    "gambia": "gm",
    "gh": "gh",
    "ghana": "gh",
    "gn": "gn",
    "guinea": "gn",
    "gw": "gw",
    "guinea bissau": "gw",
    "ke": "ke",
    "kenya": "ke",
    "ls": "ls",
    "lesotho": "ls",
    "lr": "lr",
    "liberia": "lr",
    "ly": "ly",
    "libya": "ly",
    "mg": "mg",
    "madagascar": "mg",
    "mw": "mw",
    "malawi": "mw",
    "ml": "ml",
    "mali": "ml",
    "mr": "mr",
    "mauritania": "mr",
    "mu": "mu",
    "mauritius": "mu",
    "ma": "ma",
    "morocco": "ma",
    "mz": "mz",
    "mozambique": "mz",
    "na": "na",
    "namibia": "na",
    "ne": "ne",
    "niger": "ne",
    "ng": "ng",
    "nigeria": "ng",
    "rw": "rw",
    "rwanda": "rw",
    "st": "st",
    "sao tome and principe": "st",
    "sn": "sn",
    "senegal": "sn",
    "sc": "sc",
    "seychelles": "sc",
    "sl": "sl",
    "sierra leone": "sl",
    "so": "so",
    "somalia": "so",
    "za": "za",
    "south africa": "za",
    "ss": "ss",
    "south sudan": "ss",
    "sd": "sd",
    "sudan": "sd",
    "sz": "sz",
    "swaziland": "sz",
    "eswatini": "sz",
    "tz": "tz",
    "tanzania": "tz",
    "tg": "tg",
    "togo": "tg",
    "tn": "tn",
    "tunisia": "tn",
    "ug": "ug",
    "uganda": "ug",
    "zm": "zm",
    "zambia": "zm",
    "zw": "zw",
    "zimbabwe": "zw",
    # Oceania
    "au": "au",
    "australia": "au",
    "fj": "fj",
    "fiji": "fj",
    "ki": "ki",
    "kiribati": "ki",
    "mh": "mh",
    "marshall islands": "mh",
    "fm": "fm",
    "micronesia": "fm",
    "nr": "nr",
    "nauru": "nr",
    "nz": "nz",
    "new zealand": "nz",
    "pw": "pw",
    "palau": "pw",
    "pg": "pg",
    "papua new guinea": "pg",
    "ws": "ws",
    "samoa": "ws",
    "sb": "sb",
    "solomon islands": "sb",
    "to": "to",
    "tonga": "to",
    "tv": "tv",
    "tuvalu": "tv",
    "vu": "vu",
    "vanuatu": "vu",
    # Territories and Special Cases
    "hk": "hk",
    "hong kong": "hk",
    "mo": "mo",
    "macau": "mo",
    "ps": "ps",
    "palestine": "ps",
    "re": "re",
    "reunion": "re",
    "tf": "tf",
    "french southern territories": "tf",
    "um": "um",
    "united states minor outlying islands": "um",
    "wf": "wf",
    "wallis and futuna": "wf",
    "yt": "yt",
    "mayotte": "yt",
}
