"""
Domain-specific scraping parameter recommendations for ScraperAPI.

This module provides suggested scraping parameters for specific domains based on
historical performance data. These recommendations aim to optimize success rates
based on previous usage patterns.
"""

from typing import Any, Dict, Optional
from urllib.parse import urlparse

DOMAIN_BASED_SUGGESTIONS = {
    "104.com.tw": {"premium": True, "ultra_premium": True},
    "1nce.com": {"premium": True},
    "500level.com": {"ultra_premium": True},
    "80stees.com": {"ultra_premium": True},
    "8a.pl": {"ultra_premium": True},
    "ableshop.kr": {"premium": True},
    "acmetools.com": {"ultra_premium": True},
    "action.com": {"premium": True},
    "adidas.co.uk": {"premium": True, "ultra_premium": True},
    "adidas.de": {"premium": True, "ultra_premium": True},
    "adidas.fr": {"ultra_premium": True},
    "adonait.com": {"premium": True, "ultra_premium": True},
    "adp.com": {"premium": True, "ultra_premium": True},
    "adzuna.co.uk": {"premium": True},
    "algo.monster": {"premium": True},
    "allegro.pl": {"ultra_premium": True},
    "allibo.com": {"premium": True},
    "alljobs.co.il": {"premium": True},
    "allsaints.com": {"premium": True},
    "aloyoga.com": {"premium": True, "ultra_premium": True},
    "alrugaibfurniture.com": {"ultra_premium": True},
    "amayama.com": {"ultra_premium": True},
    "amiami.com": {"ultra_premium": True},
    "analogshift.com": {"ultra_premium": True},
    "anker.com": {"premium": True},
    "antiquejewelrymall.com": {"ultra_premium": True},
    "antonline.com": {"ultra_premium": True},
    "appcast.io": {"premium": True},
    "applicantpool.com": {"ultra_premium": True},
    "applicantpro.com": {"premium": True, "ultra_premium": True},
    "applicantstack.com": {"premium": True, "ultra_premium": True},
    "apply-now.us": {"premium": True},
    "applybe.com": {"premium": True},
    "applytojob.com": {"premium": True, "ultra_premium": True},
    "appone.com": {"premium": True, "ultra_premium": True},
    "arbetsformedlingen.se": {"premium": True},
    "arcb.com": {"premium": True},
    "architecturaldepot.com": {"ultra_premium": True},
    "archive.org": {"ultra_premium": True},
    "arcteryx.com": {"ultra_premium": True},
    "artistcollectives.org": {"ultra_premium": True},
    "ascotandhart.com": {"ultra_premium": True},
    "ashbyhq.com": {"premium": True, "ultra_premium": True},
    "atsondemand.com": {"premium": True},
    "aurumandgrey.com": {"ultra_premium": True},
    "auto1-group.com": {"premium": True},
    "autocasion.com": {"premium": True},
    "autodoc.gr": {"ultra_premium": True},
    "autoplac.pl": {"ultra_premium": True},
    "avature.net": {"premium": True, "ultra_premium": True},
    "babyland.pl": {"ultra_premium": True},
    "bachaaparty.com": {"ultra_premium": True},
    "bagista.co.uk": {"ultra_premium": True},
    "baitoru.com": {"premium": True},
    "baltini.com": {"premium": True},
    "bamboohr.com": {"premium": True},
    "basic-fit.com": {"premium": True},
    "basicos.mx": {"ultra_premium": True},
    "bayut.com": {"premium": True},
    "bbb.org": {"premium": True, "ultra_premium": True},
    "beactivewear.com.au": {"ultra_premium": True},
    "bemmelenkroon.nl": {"premium": True},
    "benq.com": {"premium": True},
    "bestbuy.com": {"premium": True, "ultra_premium": True},
    "bewakoof.com": {"premium": True},
    "binance.com": {"ultra_premium": True},
    "bing.com": {"premium": True, "ultra_premium": True},
    "birthday.se": {"ultra_premium": True},
    "bitcoinmagazine.nl": {"ultra_premium": True},
    "bizbuysell.com": {"premium": True},
    "bizno.net": {"premium": True},
    "blinkit.com": {"premium": True},
    "bloomberg.com": {"ultra_premium": True},
    "bloomingdales.com": {"premium": True},
    "bmwgroup.jobs": {"premium": True},
    "bol.com": {"ultra_premium": True},
    "booking.com": {"premium": True},
    "bookmyshow.com": {"premium": True},
    "brainly.com": {"premium": True},
    "bravestarselvage.com": {"ultra_premium": True},
    "brooksrunning.com": {"premium": True},
    "brunellocucinelli.com": {"premium": True},
    "btc-echo.de": {"ultra_premium": True},
    "buckle.com": {"ultra_premium": True},
    "burga.com": {"ultra_premium": True},
    "butterlaneantiques.com": {"ultra_premium": True},
    "career-cloud.asia": {"premium": True},
    "careerbuilder.com": {"ultra_premium": True},
    "carfax.com": {"premium": True},
    "cariuma.com": {"ultra_premium": True},
    "carrefour.be": {"ultra_premium": True},
    "cea.com.br": {"premium": True},
    "cea.gov.sg": {"premium": True},
    "ceneo.pl": {"premium": True, "ultra_premium": True},
    "centrakor.com": {"premium": True},
    "cernucci.com": {"ultra_premium": True},
    "chattr.ai": {"premium": True},
    "cheapundies.com": {"ultra_premium": True},
    "chegg.com": {"premium": True},
    "chewy.com": {"ultra_premium": True},
    "chime.com": {"ultra_premium": True},
    "choicehotels.com": {"premium": True},
    "choicemusicla.com": {"ultra_premium": True},
    "cimri.com": {"premium": True},
    "cloudbet.com": {"premium": True},
    "cloudpack.jp": {"premium": True},
    "coastsoccer.us": {"premium": True},
    "coconala.com": {"premium": True},
    "coin-update.de": {"ultra_premium": True},
    "coinacademy.fr": {"ultra_premium": True},
    "coiteuxhyundai.com": {"ultra_premium": True},
    "colettehayman.com.au": {"ultra_premium": True},
    "coupang.com": {"ultra_premium": True},
    "courts.com.my": {"premium": True},
    "courts.com.sg": {"premium": True},
    "craigslist.org": {"ultra_premium": True},
    "crateandbarrel.com": {"ultra_premium": True},
    "crunchbase.com": {"ultra_premium": True},
    "currys.co.uk": {"ultra_premium": True},
    "cyberbackgroundchecks.com": {"ultra_premium": True},
    "cylex.ro": {"premium": True},
    "darty.com": {"ultra_premium": True},
    "darwinbox.in": {"premium": True},
    "deadrockers.net": {"ultra_premium": True},
    "decathlon.fr": {"premium": True},
    "deckoutgaming.ca": {"ultra_premium": True},
    "decoexchange.com": {"ultra_premium": True},
    "dejobs.org": {"premium": True},
    "desicallyethnic.com": {"ultra_premium": True},
    "designboom.com": {"premium": True},
    "dexscreener.com": {"ultra_premium": True},
    "dgprodchatbotstorage.blob.core.windows.net": {"premium": True},
    "dienmayxanh.com": {"premium": True},
    "digikey.cn": {"premium": True},
    "digikey.com": {"premium": True, "ultra_premium": True},
    "digikey.de": {"ultra_premium": True},
    "digitec.ch": {"premium": True},
    "doordash.com": {"premium": True},
    "dormify.com": {"ultra_premium": True},
    "dressx.com": {"ultra_premium": True},
    "drmartens.com": {"ultra_premium": True},
    "drumcenternh.com": {"ultra_premium": True},
    "e-motors.fr": {"premium": True},
    "e.leclerc": {"premium": True},
    "ebay.com": {"premium": True},
    "echt-susteren.nl": {"premium": True},
    "element14.com": {"premium": True},
    "elgiganten.dk": {"premium": True},
    "elgiganten.se": {"premium": True},
    "en-japan.com": {"premium": True},
    "energymuse.com": {"ultra_premium": True},
    "eniro.se": {"ultra_premium": True},
    "erli.pl": {"ultra_premium": True},
    "etsy.com": {"premium": True, "ultra_premium": True},
    "eventim.com": {"ultra_premium": True},
    "eventim.de": {"ultra_premium": True},
    "excelmale.com": {"premium": True},
    "exercism.org": {"premium": True},
    "explorimmoneuf.com": {"ultra_premium": True},
    "extensishrtalent.com": {"premium": True},
    "extraspace.com": {"ultra_premium": True},
    "facebook.com": {"premium": True},
    "falabella.com": {"premium": True},
    "falabella.com.pe": {"premium": True},
    "fanaticscollect.com": {"ultra_premium": True},
    "fanduel.com": {"ultra_premium": True},
    "farmrio.com": {"premium": True, "ultra_premium": True},
    "fastpeoplesearch.com": {"ultra_premium": True},
    "feel22.com": {"ultra_premium": True},
    "fentybeauty.com": {"premium": True, "ultra_premium": True},
    "ffib.es": {"premium": True},
    "finishline.com": {"premium": True},
    "fiverr.com": {"premium": True},
    "flipkart.com": {"premium": True},
    "flyfrontier.com": {"ultra_premium": True},
    "fnac.be": {"premium": True},
    "fnac.es": {"premium": True},
    "fnac.pt": {"premium": True},
    "footlocker.com": {"ultra_premium": True},
    "forasna.com": {"premium": True},
    "forloveandlemons.com": {"ultra_premium": True},
    "foundit.com.ph": {"premium": True},
    "foundit.hk": {"premium": True},
    "foundit.id": {"premium": True},
    "foundit.in": {"premium": True, "ultra_premium": True},
    "foundit.my": {"premium": True},
    "foundit.sg": {"premium": True, "ultra_premium": True},
    "founditgulf.com": {"premium": True, "ultra_premium": True},
    "francetravail.fr": {"premium": True, "ultra_premium": True},
    "freshteam.com": {"premium": True, "ultra_premium": True},
    "futgal.es": {"premium": True},
    "galletuki.com": {"ultra_premium": True},
    "gamedaycouture.com": {"ultra_premium": True},
    "garagegrowngear.com": {"premium": True},
    "geeksforgeeks.org": {"premium": True},
    "github.com": {"premium": True},
    "gitionline.com": {"ultra_premium": True},
    "glassdoor.com": {"premium": True},
    "glassesusa.com": {"ultra_premium": True},
    "globalindustrial.com": {"ultra_premium": True},
    "goat.com": {"premium": True},
    "golfroots.com": {"ultra_premium": True},
    "goodrx.com": {"ultra_premium": True},
    "gosportme.com": {"ultra_premium": True},
    "gotoliquorstore.com": {"ultra_premium": True},
    "governmentjobs.com": {"premium": True, "ultra_premium": True},
    "grandecosmetics.com": {"premium": True},
    "groupe-seloger.com": {"ultra_premium": True},
    "growtropicals.com": {"ultra_premium": True},
    "hanogram.com": {"ultra_premium": True},
    "happyjewelers.com": {"ultra_premium": True},
    "harri.com": {"premium": True, "ultra_premium": True},
    "havochobby.com": {"ultra_premium": True},
    "hepsiburada.com": {"premium": True},
    "hessen.de": {"ultra_premium": True},
    "hirecentric.com": {"premium": True},
    "hireology.com": {"premium": True, "ultra_premium": True},
    "hiringthing.com": {"premium": True},
    "hitta.se": {"premium": True},
    "hobbiesville.com": {"ultra_premium": True},
    "hoka.com": {"premium": True},
    "hokuohkurashi.com": {"premium": True},
    "homedepot.ca": {"premium": True},
    "homedepot.com": {"premium": True},
    "homefieldapparel.com": {"ultra_premium": True},
    "homegate.ch": {"premium": True},
    "hoober.com": {"ultra_premium": True},
    "hostedats.com": {"premium": True},
    "icarros.com.br": {"premium": True},
    "icims.com": {"premium": True},
    "idealista.com": {"premium": True},
    "idealista.it": {"premium": True},
    "ikea.com": {"premium": True, "ultra_premium": True},
    "imusic.dk": {"premium": True},
    "incu.com": {"ultra_premium": True},
    "indeed.com": {"ultra_premium": True},
    "inmuebles24.com": {"ultra_premium": True},
    "investing.com": {"premium": True},
    "inweaveindia.com": {"ultra_premium": True},
    "iparts.pl": {"ultra_premium": True},
    "irecruit-us.com": {"premium": True},
    "isolvedhire.com": {"ultra_premium": True},
    "job4all.co.il": {"premium": True},
    "jobappnetwork.com": {"premium": True, "ultra_premium": True},
    "jobconvo.com": {"premium": True, "ultra_premium": True},
    "jobilla.com": {"premium": True},
    "jobs.net": {"premium": True, "ultra_premium": True},
    "jobvite.com": {"premium": True, "ultra_premium": True},
    "jooble.org": {"premium": True},
    "jora.com": {"premium": True},
    "kallidusrecruit.com": {"premium": True},
    "kindredblack.com": {"ultra_premium": True},
    "kitjob.in": {"premium": True},
    "klix.ba": {"premium": True},
    "knittedbelle.com": {"ultra_premium": True},
    "kohls.com": {"ultra_premium": True},
    "kortnijeane.com": {"ultra_premium": True},
    "kream.co.kr": {"premium": True},
    "ktalnews.com": {"premium": True},
    "kwai.com": {"premium": True},
    "lacentrale.fr": {"ultra_premium": True},
    "landea.gr": {"ultra_premium": True},
    "lazada.co.th": {"premium": True},
    "lazada.com.my": {"premium": True},
    "lazada.sg": {"premium": True},
    "lbank.com": {"ultra_premium": True},
    "ldlc.pro": {"premium": True},
    "leagueoutfitters.com": {"ultra_premium": True},
    "leboncoin.fr": {"ultra_premium": True},
    "leclercdrive.fr": {"ultra_premium": True},
    "legacy.com": {"ultra_premium": True},
    "lenovo.com": {"premium": True},
    "leroymerlin.fr": {"ultra_premium": True},
    "lespetitesjupesdeprune.com": {"premium": True},
    "licorea.com": {"ultra_premium": True},
    "lieferando.at": {"ultra_premium": True},
    "linkedin.com": {"ultra_premium": True},
    "liverpool.com.mx": {"premium": True},
    "lookfantastic.com.au": {"ultra_premium": True},
    "looktwice.co": {"ultra_premium": True},
    "louisvuitton.com": {"ultra_premium": True},
    "lovecherish.com": {"ultra_premium": True},
    "lowes.com": {"premium": True, "ultra_premium": True},
    "lululemon.co.uk": {"ultra_premium": True},
    "lululemon.com.au": {"ultra_premium": True},
    "maap.cc": {"ultra_premium": True},
    "manomano.fr": {"ultra_premium": True},
    "manpower.de": {"premium": True},
    "marathonbet.com": {"premium": True},
    "martineztools.com": {"ultra_premium": True},
    "maxibazar.fr": {"premium": True},
    "mcalistersdeli.com": {"premium": True},
    "mcelhinneys.com": {"ultra_premium": True},
    "mediamarkt.de": {"premium": True},
    "mediamarkt.hu": {"premium": True},
    "mediamarkt.pl": {"premium": True},
    "mediaworld.it": {"premium": True},
    "medium.com": {"premium": True},
    "megaknihy.sk": {"ultra_premium": True},
    "melindamaria.com": {"premium": True},
    "mercadolibre.com.co": {"premium": True},
    "mercadolibre.com.mx": {"premium": True},
    "mercadolivre.com.br": {"premium": True},
    "mercari.com": {"premium": True},
    "merimeri.com": {"ultra_premium": True},
    "merinfo.se": {"premium": True},
    "metamask.io": {"premium": True},
    "miamisample.com": {"ultra_premium": True},
    "mightyrecruiter.com": {"premium": True},
    "milanuncios.com": {"premium": True},
    "mini.co.uk": {"ultra_premium": True},
    "mini.fr": {"ultra_premium": True},
    "mini.it": {"ultra_premium": True},
    "mini.nl": {"ultra_premium": True},
    "mini.pt": {"ultra_premium": True},
    "mini.ro": {"ultra_premium": True},
    "minne.com": {"premium": True},
    "modernkomfort.ca": {"ultra_premium": True},
    "modivo.cz": {"ultra_premium": True},
    "mollusksurfshop.com": {"ultra_premium": True},
    "moneyforward.com": {"premium": True},
    "monster.co.th": {"premium": True},
    "monster.com.vn": {"premium": True},
    "monster.io": {"ultra_premium": True},
    "mrkoll.se": {"premium": True},
    "multimax.net": {"ultra_premium": True},
    "musubi-furoshiki.com": {"premium": True},
    "nagano-market.jp": {"premium": True, "ultra_premium": True},
    "naver.com": {"premium": True},
    "ncoreplat.com": {"premium": True},
    "newark.com": {"premium": True},
    "newhome.ch": {"premium": True},
    "newyorkdress.com": {"ultra_premium": True},
    "next.ae": {"premium": True},
    "nike.com": {"premium": True},
    "ninacampbell.com": {"ultra_premium": True},
    "ninjatransfers.com": {"ultra_premium": True},
    "nishatlinenuae.com": {"ultra_premium": True},
    "nobullproject.com": {"ultra_premium": True},
    "noon.com": {"premium": True},
    "nordstrom.com": {"premium": True},
    "nordstromrack.com": {"ultra_premium": True},
    "nucleusportland.com": {"ultra_premium": True},
    "nykaafashion.com": {"premium": True},
    "oasisrecruit.com": {"premium": True},
    "oceannailsupply.com": {"ultra_premium": True},
    "oceannailsupply.myshopify.com": {"ultra_premium": True},
    "oliveateliers.com": {"ultra_premium": True},
    "oneill.com": {"ultra_premium": True},
    "onitsukatiger.com": {"premium": True},
    "opensea.io": {"premium": True},
    "openstreetmap.org": {"ultra_premium": True},
    "originsnyc.com": {"ultra_premium": True},
    "otakumode.com": {"premium": True},
    "otomoto.pl": {"ultra_premium": True},
    "outregallery.com": {"ultra_premium": True},
    "pacsun.com": {"ultra_premium": True},
    "paradox.ai": {"premium": True},
    "parlamentsspiegel.de": {"ultra_premium": True},
    "parliament.uk": {"ultra_premium": True},
    "paycomonline.net": {"premium": True, "ultra_premium": True},
    "paylocity.com": {"premium": True, "ultra_premium": True},
    "pelacase.com": {"ultra_premium": True},
    "personio.com": {"premium": True, "ultra_premium": True},
    "personio.de": {"premium": True, "ultra_premium": True},
    "petbase.eu": {"premium": True},
    "pfg.fr": {"premium": True},
    "piperloucollection.com": {"ultra_premium": True},
    "pitchbook.com": {"ultra_premium": True},
    "please.co": {"premium": True},
    "pokemoncenter-online.com": {"ultra_premium": True},
    "pontofrio.com.br": {"ultra_premium": True},
    "popular.jewelry": {"ultra_premium": True},
    "poshpeanut.com": {"premium": True},
    "prevueaps.com": {"ultra_premium": True},
    "pricerunner.dk": {"premium": True},
    "pricerunner.se": {"premium": True},
    "prismhr-hire.com": {"premium": True},
    "property24.com": {"premium": True},
    "prospective.ch": {"premium": True},
    "pumpa.eu": {"premium": True},
    "q84sale.com": {"premium": True},
    "quora.com": {"premium": True},
    "rabbitscams.sex": {"premium": True},
    "rabbitsreviews.com": {"premium": True},
    "ralphlauren.com": {"ultra_premium": True},
    "ralphlauren.fr": {"ultra_premium": True},
    "rarible.com": {"premium": True},
    "rastah.co": {"ultra_premium": True},
    "ratemds.com": {"premium": True},
    "ratsit.se": {"premium": True},
    "realadvisor.ch": {"ultra_premium": True},
    "realcommercial.com.au": {"ultra_premium": True},
    "realestate.com.au": {"ultra_premium": True},
    "realtor.com": {"premium": True, "ultra_premium": True},
    "rebuyengine.com": {"ultra_premium": True},
    "recruitingbypaycor.com": {"premium": True},
    "reddit.com": {"premium": True},
    "redfin.com": {"ultra_premium": True},
    "relaygoods.com": {"premium": True},
    "rent.com": {"premium": True},
    "restockar.com": {"ultra_premium": True},
    "retrospekt.com": {"ultra_premium": True},
    "ripley.com.pe": {"ultra_premium": True},
    "rippling-ats.com": {"premium": True},
    "rockauto.com": {"premium": True},
    "rs-online.com": {"premium": True, "ultra_premium": True},
    "ruggable.co.uk": {"ultra_premium": True},
    "saashr.com": {"premium": True, "ultra_premium": True},
    "salesforce-sites.com": {"premium": True, "ultra_premium": True},
    "sallybeauty.com": {"ultra_premium": True},
    "samsclub.com": {"ultra_premium": True},
    "saturn.de": {"premium": True},
    "sbishinseibank.co.jp": {"premium": True},
    "schooljobs.com": {"premium": True, "ultra_premium": True},
    "scope.co.il": {"premium": True},
    "sealmg.com": {"premium": True},
    "seattletimes.com": {"premium": True},
    "secnews.gr": {"premium": True},
    "securitieslawyer.com": {"premium": True},
    "sephora.com": {"premium": True},
    "shi.ca": {"ultra_premium": True},
    "shi.com": {"ultra_premium": True},
    "shopthesoho.com": {"ultra_premium": True},
    "sillygirlclub.com": {"ultra_premium": True},
    "simplyhired.com": {"premium": True},
    "singlecare.com": {"ultra_premium": True},
    "siopaella.com": {"ultra_premium": True},
    "skinsociety.me": {"ultra_premium": True},
    "skroutz.gr": {"premium": True},
    "skylinebeautysupply.com": {"ultra_premium": True},
    "slamcity.com": {"ultra_premium": True},
    "slotcatalog.com": {"premium": True},
    "smartwool.com": {"ultra_premium": True},
    "soccerway.com": {"ultra_premium": True},
    "solides.com.br": {"ultra_premium": True},
    "sostrenegrene.com": {"premium": True},
    "spearmintlove.com": {"ultra_premium": True},
    "spglobal.com": {"ultra_premium": True},
    "squarespace.com": {"premium": True, "ultra_premium": True},
    "stackoverflow.com": {"premium": True},
    "stokomani.fr": {"premium": True},
    "substack.com": {"premium": True},
    "sundancecatalog.com": {"ultra_premium": True},
    "sundayswagger.com": {"ultra_premium": True},
    "supleks.jp": {"premium": True},
    "suratkargo.com.tr": {"premium": True},
    "swag.golf": {"ultra_premium": True},
    "szirojewelry.com": {"ultra_premium": True},
    "szse.cn": {"ultra_premium": True},
    "tal.net": {"premium": True},
    "taleo.net": {"premium": True, "ultra_premium": True},
    "target.com": {"ultra_premium": True},
    "tedk12.com": {"premium": True, "ultra_premium": True},
    "tentree.ca": {"ultra_premium": True},
    "tentree.co.uk": {"ultra_premium": True},
    "tentree.eu": {"ultra_premium": True},
    "teressafoglia.com": {"ultra_premium": True},
    "teva.com": {"ultra_premium": True},
    "thalia.de": {"premium": True},
    "thbaker.co.uk": {"ultra_premium": True},
    "thebagriculture.com": {"ultra_premium": True},
    "thegioididong.com": {"premium": True},
    "thelocal.com": {"premium": True},
    "thepornmap.com": {"premium": True},
    "thepremierstore.com": {"ultra_premium": True},
    "thepulseboutique.com": {"ultra_premium": True},
    "thestreet.com": {"ultra_premium": True},
    "tiffany.co.jp": {"premium": True},
    "tiktok.com": {"premium": True, "ultra_premium": True},
    "tjx.com": {"ultra_premium": True},
    "tme.eu": {"premium": True},
    "tommy.com": {"ultra_premium": True},
    "topodesigns.com": {"premium": True},
    "trabajos.com": {"premium": True},
    "trabalhabrasil.com.br": {"premium": True},
    "tradeinn.com": {"premium": True},
    "trendyol.com": {"premium": True},
    "trescrucesjoyeria.com": {"ultra_premium": True},
    "tripadvisor.com": {"premium": True},
    "truepeoplesearch.com": {"ultra_premium": True},
    "trulia.com": {"premium": True},
    "tudosobreprodutos.com.br": {"premium": True, "ultra_premium": True},
    "tumi.com": {"ultra_premium": True},
    "tyomarkkinatori.fi": {"premium": True},
    "ubaldi.com": {"ultra_premium": True},
    "udemy.com": {"ultra_premium": True},
    "ukg.net": {"premium": True},
    "ultipro.ca": {"premium": True},
    "ultipro.com": {"premium": True},
    "uncrate.com": {"ultra_premium": True},
    "uniqlo.com": {"premium": True},
    "upbit.com": {"premium": True},
    "upplysning.se": {"ultra_premium": True},
    "urbanoutfitters.com": {"ultra_premium": True},
    "vaaree.com": {"ultra_premium": True},
    "valabasas.com": {"ultra_premium": True},
    "vans.com": {"premium": True},
    "vanwall.com": {"ultra_premium": True},
    "vectorinc.co.jp": {"premium": True},
    "verizon.com": {"premium": True},
    "vivareal.com.br": {"ultra_premium": True},
    "vividseats.com": {"premium": True},
    "voylla.com": {"ultra_premium": True},
    "vzw.com": {"premium": True},
    "wallshoppe.com": {"ultra_premium": True},
    "walmart.com": {"ultra_premium": True},
    "wayfair.ca": {"premium": True},
    "webbyawards.com": {"premium": True},
    "webpt.com": {"premium": True},
    "webuy.com": {"premium": True},
    "welcomekit.co": {"premium": True},
    "welcometothejungle.com": {"premium": True, "ultra_premium": True},
    "werkenbijstrukton.nl": {"premium": True},
    "whsmith.co.uk": {"ultra_premium": True},
    "wikipedia.org": {"premium": True},
    "wizehire.com": {"premium": True},
    "woodcraft.com": {"ultra_premium": True},
    "workable.com": {"premium": True, "ultra_premium": True},
    "worldrugbyshop.com": {"premium": True},
    "worten.pt": {"ultra_premium": True},
    "x-kom.pl": {"ultra_premium": True},
    "yad2.co.il": {"premium": True},
    "yaencontre.com": {"ultra_premium": True},
    "yahoo.com": {"premium": True, "ultra_premium": True},
    "yellowpop.com": {"ultra_premium": True},
    "yelp.com": {"premium": True, "ultra_premium": True},
    "yoox.com": {"ultra_premium": True},
    "youbooze.com": {"ultra_premium": True},
    "youngla.com": {"ultra_premium": True},
    "youtube.com": {"premium": True, "ultra_premium": True},
    "zanvis.com": {"ultra_premium": True},
    "zgoperfumery.com": {"ultra_premium": True},
    "zillow.com": {"ultra_premium": True},
    "ziprecruiter.com": {"premium": True},
    "zkh.com": {"ultra_premium": True},
    "zkh360.com": {"ultra_premium": True},
    "zohorecruit.com": {"premium": True, "ultra_premium": True},
    "zohorecruit.eu": {"premium": True},
    "zoominfo.com": {"ultra_premium": True},
    "zoro.com": {"premium": True, "ultra_premium": True},
    "zozo.jp": {"premium": True},
    "zumiez.com": {"premium": True},
}


def get_domain_based_suggestions(url: str) -> Optional[Dict[str, Any]]:
    """
    Get the domain-specific suggested parameters for a given URL.

    Args:
        url: The URL to get suggested parameters for

    Returns:
        Dictionary with domain-specific parameters or None if not found
    """
    try:
        parsed_url = urlparse(url)
        domain = parsed_url.netloc.lower()

        if domain.startswith("www."):
            domain = domain[4:]

        if domain in DOMAIN_BASED_SUGGESTIONS:
            return DOMAIN_BASED_SUGGESTIONS[domain]

        # Try parent domain match (e.g., subdomain.example.com -> example.com)
        parts = domain.split(".")
        if len(parts) > 2:
            parent_domain = ".".join(parts[-2:])
            if parent_domain in DOMAIN_BASED_SUGGESTIONS:
                return DOMAIN_BASED_SUGGESTIONS[parent_domain]

        return None
    except Exception:
        return None


def apply_domain_suggestions(
    url: str, current_params: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Apply domain-specific parameter suggestions to current parameters if available.
    Only applies parameters that aren't explicitly set (None values).

    Args:
        url: The URL to get suggested parameters for
        current_params: Dictionary of current parameters

    Returns:
        Updated parameters dictionary
    """
    suggested_parameters = get_domain_based_suggestions(url)
    if not suggested_parameters:
        return current_params

    result = current_params.copy()

    # Only apply when no value has been explicitly set
    for key, value in suggested_parameters.items():
        if key in result and result[key] is None:
            result[key] = value

    # Handle mutually exclusive premium and ultra_premium
    if result.get("premium") and result.get("ultra_premium"):
        # If both are set to True, prioritize premium
        result["ultra_premium"] = False

    return result
